version: "3.4"


services:
  rezepteApp:
    image: rezepte
    build: .
    ports:
      - "7001:3001"
    # volumes:
    #   - ./:/usr/src/app/ 
    # working_dir: /usr/src/app

    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app

    depends_on:
      - mysql
    links:
      - mysql:mysql  
    env_file:
      - .env

  mysql:
    image: mysql:latest
    container_name: mysqlContainer
    command: --default-authentication-plugin=mysql_native_password
    env_file:
      - .env    
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/:/docker-entrypoint-initdb.d
    expose:
      - '3306'        
